package api.Utils;

public class Credentials {

    public static final String URL = "https://app.getblend.com/api/2/";
    public static final String token = "api2key 2qG9dm3WtVB7YZM6JQhb:80f75518d78cfe53c3e300f9c8bc39e5";

    public static final String[] supportedLanguages = new String[]
            {"English",
                    "Russian",
                    "Afrikaans",
                    "Albanian",
                    "Amharic",
                    "Arabic",
                    "Arabic (Egyptian)",
                    "Arabic (Gulf)",
                    "Arabic (Levantine)",
                    "Arabic (Maghrebi)",
                    "Armenian",
                    "Assamese",
                    "Azerbaijani",
                    "Basque",
                    "Belarussian",
                    "Bengali",
                    "Bosnian",
                    "Bulgarian",
                    "Burmese",
                    "Catalan",
                    "Chinese Cantonese",
                    "Croatian",
                    "Czech",
                    "Danish",
                    "Dari",
                    "Dutch",
                    "Estonian",
                    "Finnish",
                    "Flemish (Belgian)",
                    "French",
                    "French (Canadian)",
                    "Galician",
                    "Georgian",
                    "German",
                    "Greek",
                    "Gujarati",
                    "Haitian Creole",
                    "Hausa",
                    "Hebrew",
                    "Hindi",
                    "Hungarian",
                    "Icelandic",
                    "Indonesian",
                    "Italian",
                    "Japanese",
                    "Kannada",
                    "Kazakh",
                    "Khmer",
                    "Korean",
                    "Kurdish",
                    "Lao",
                    "Latvian",
                    "Lithuanian",
                    "Macedonian",
                    "Malay",
                    "Malayalam",
                    "Maltese",
                    "Marathi",
                    "Mongolian",
                    "Montenegrin",
                    "Nepali",
                    "Norwegian",
                    "Pashto",
                    "Persian",
                    "Polish",
                    "Portuguese (Brazil)",
                    "Portuguese (Portugal)",
                    "Punjabi",
                    "Romanian",
                    "Serbian (Cyrillic)",
                    "Serbian (Latin)",
                    "Simplified Chinese (Mainland China)",
                    "Sinhala",
                    "Slovak",
                    "Slovenian (Slovene)",
                    "Somali",
                    "Spanish",
                    "Spanish (Latin-America)",
                    "Spanish (Mexico)",
                    "Swahili",
                    "Swedish",
                    "Swiss French",
                    "Swiss German",
                    "Tagalog",
                    "Tajik",
                    "Tamil",
                    "Telugu",
                    "Thai",
                    "Tigrinya",
                    "Traditional Chinese (HK)",
                    "Traditional Chinese (Taiwan)",
                    "Turkish",
                    "Ukrainian",
                    "Urdu",
                    "Uzbek",
                    "Vietnamese",
                    "Welsh",
                    "Xhosa",
                    "Yoruba",
                    "Zulu"};


    public static final String[] sourceLanguages = new String[]
            {"Afrikaans",
                    "Albanian",
                    "Amharic",
                    "Arabic",
                    "Armenian",
                    "Assamese",
                    "Azerbaijani",
                    "Bengali",
                    "Bengali (Romanized)",
                    "Bosnian",
                    "Breton",
                    "Bulgarian",
                    "Burmese",
                    "Catalan",
                    "Cebuano",
                    "Chinese Cantonese",
                    "Czech",
                    "Danish",
                    "Dutch",
                    "English",
                    "English (AU)",
                    "English (UK)",
                    "English (US)",
                    "Estonian",
                    "Finnish",
                    "French",
                    "French (Canadian)",
                    "Galician",
                    "Georgian",
                    "German",
                    "Greek",
                    "Gujarati",
                    "Haitian Creole",
                    "Hebrew",
                    "Hindi",
                    "Hungarian",
                    "Icelandic",
                    "Indonesian",
                    "Italian",
                    "Japanese",
                    "Kannada",
                    "Khmer",
                    "Korean",
                    "Lao",
                    "Latvian",
                    "Lithuanian",
                    "Macedonian",
                    "Malay",
                    "Malayalam",
                    "Maltese",
                    "Marathi",
                    "Nepali",
                    "Norwegian",
                    "Pashto",
                    "Persian",
                    "Polish",
                    "Portuguese (Brazil)",
                    "Portuguese (Portugal)",
                    "Punjabi",
                    "Romanian",
                    "Russian",
                    "Serbian (Cyrillic)",
                    "Simplified Chinese (Mainland China)",
                    "Sinhala",
                    "Slovak",
                    "Slovenian (Slovene)",
                    "Spanish",
                    "Spanish (Latin-America)",
                    "Spanish (Mexico)",
                    "Swahili",
                    "Swedish",
                    "Tagalog",
                    "Tamil",
                    "Tamil (Romanized)",
                    "Thai",
                    "Traditional Chinese (HK)",
                    "Traditional Chinese (Taiwan)",
                    "Turkish",
                    "Ukrainian",
                    "Urdu",
                    "Uzbek",
                    "Vietnamese"};
    public static final String[] targetLanguages =
            {"English",
                    "English (UK)",
                    "Arabic",
                    "French",
                    "Armenian",
                    "Azerbaijani",
                    "Bulgarian",
                    "Spanish",
                    "Cebuano",
                    "Chinese Cantonese",
                    "Czech",
                    "Danish",
                    "Norwegian",
                    "Dutch",
                    "Afrikaans",
                    "Albanian",
                    "Amharic",
                    "Arabic (Egyptian)",
                    "Arabic (Formal)",
                    "Arabic (Gulf)",
                    "Arabic (Iraqi)",
                    "Arabic (Levantine)",
                    "Arabic (Maghrebi)",
                    "Assamese",
                    "Bambara",
                    "Belarussian",
                    "Bengali",
                    "Bhojpuri",
                    "Bosnian",
                    "Burmese",
                    "Catalan",
                    "Croatian",
                    "Dari",
                    "Estonian",
                    "Finnish",
                    "Flemish (Belgian)",
                    "French (Canadian)",
                    "Galician",
                    "Ganda",
                    "Georgian",
                    "German",
                    "Greek",
                    "Gujarati",
                    "Gusii",
                    "Haitian Creole",
                    "Hebrew",
                    "Hindi",
                    "Hungarian",
                    "Icelandic",
                    "Ilocano",
                    "Indonesian",
                    "Italian",
                    "Japanese",
                    "Kalenjin",
                    "Kamba",
                    "Kannada",
                    "Kazakh",
                    "Khmer",
                    "Kikuyu",
                    "Kinyarwanda",
                    "Kongo",
                    "Korean",
                    "Lao",
                    "Latvian",
                    "Lithuanian",
                    "Luo",
                    "Macedonian",
                    "Maithili",
                    "Malay",
                    "Malayalam",
                    "Maltese",
                    "Marathi",
                    "Mongolian",
                    "Montenegrin",
                    "Nepali",
                    "Pashto",
                    "Persian",
                    "Polish",
                    "Portuguese (Brazil)",
                    "Portuguese (Portugal)",
                    "Punjabi",
                    "Romanian",
                    "Russian",
                    "Serbian (Cyrillic)",
                    "Serbian (Latin)",
                    "Simplified Chinese (Mainland China)",
                    "Sinhala",
                    "Slovak",
                    "Slovenian (Slovene)",
                    "Somali",
                    "Southern Sotho",
                    "Spanish (Latin-America)",
                    "Spanish (Mexico)",
                    "Swahili",
                    "Swedish",
                    "Swiss German",
                    "Tagalog",
                    "Tajik",
                    "Tamil",
                    "Tamil (Romanized)",
                    "Telugu",
                    "Thai",
                    "Traditional Chinese (HK)",
                    "Traditional Chinese (Taiwan)",
                    "Tswana",
                    "Turkish",
                    "Ukrainian",
                    "Urdu",
                    "Uzbek",
                    "Vietnamese",
                    "Xhosa",
                    "Yoruba",
                    "Zulu",
                    "Breton",
                    "English (US)"};
}
